// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg_g4mCDllV_QKQTsjEpbNekkQ9usqD_g',
    appId: '1:897109921824:android:ce87daf8d5bf4736f2ec45',
    messagingSenderId: '897109921824',
    projectId: 'edututorapps',
    storageBucket: 'edututorapps.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9KP9gZxATqhW4HJ7753rAGYCfZ_6HdtE',
    appId: '1:897109921824:web:9413f6d592cb38bdf2ec45',
    messagingSenderId: '897109921824',
    projectId: 'edututorapps',
    authDomain: 'edututorapps.firebaseapp.com',
    storageBucket: 'edututorapps.firebasestorage.app',
    measurementId: 'G-G6C9LJCQ1V',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMkcD7H79XPTY4uON0D3aF0tyrX2x6T3U',
    appId: '1:897109921824:ios:379056b1a1c3b873f2ec45',
    messagingSenderId: '897109921824',
    projectId: 'edututorapps',
    storageBucket: 'edututorapps.firebasestorage.app',
    iosBundleId: 'com.example.edututormobile',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMkcD7H79XPTY4uON0D3aF0tyrX2x6T3U',
    appId: '1:897109921824:ios:379056b1a1c3b873f2ec45',
    messagingSenderId: '897109921824',
    projectId: 'edututorapps',
    storageBucket: 'edututorapps.firebasestorage.app',
    iosBundleId: 'com.example.edututormobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9KP9gZxATqhW4HJ7753rAGYCfZ_6HdtE',
    appId: '1:897109921824:web:4ed7689ae6744686f2ec45',
    messagingSenderId: '897109921824',
    projectId: 'edututorapps',
    authDomain: 'edututorapps.firebaseapp.com',
    storageBucket: 'edututorapps.firebasestorage.app',
    measurementId: 'G-ZBX2EGHJ09',
  );

}